set.seed(120)
x <- rnorm(n = 1000, mean = 5, sd=5)
y <- rnorm(n = 1000, mean = 15, sd=5)
pdf("output/schematic_of_niche.pdf")
plot(density(x), xlim=c(-10, 35), col="red3", main="", xlab = "Sea surface temperature (°C)", lwd = 2, ylim=c(0, 0.1))
lines(density(y), col="steelblue", lwd=2)
abline(v = mean(x), col="red3", lwd = 1.5, lty=2)
abline(v = mean(y), col="steelblue", lwd = 1.5, lty=2)
dev.off()